//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPPL2Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfoResponse", Namespace="http://www.serviceobjects.com")]
    public partial class PhoneInfoResponse : object
    {
        
        private GPPL2Service.PhoneInfoResult PhoneInfoField;
        
        private GPPL2Service.GPPL2Error ErrorField;
        
        private string[] DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GPPL2Service.PhoneInfoResult PhoneInfo
        {
            get
            {
                return this.PhoneInfoField;
            }
            set
            {
                this.PhoneInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GPPL2Service.GPPL2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string[] Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfoResult", Namespace="http://www.serviceobjects.com")]
    public partial class PhoneInfoResult : object
    {
        
        private GPPL2Service.Provider ProviderField;
        
        private GPPL2Service.Contact[] ContactsField;
        
        private string SMSAddressField;
        
        private string MMSAddressField;
        
        private string DateFirstSeenField;
        
        private string DateOfPortingField;
        
        private string NoteCodesField;
        
        private string NoteDescriptionsField;
        
        private string TokensUsedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GPPL2Service.Provider Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GPPL2Service.Contact[] Contacts
        {
            get
            {
                return this.ContactsField;
            }
            set
            {
                this.ContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SMSAddress
        {
            get
            {
                return this.SMSAddressField;
            }
            set
            {
                this.SMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MMSAddress
        {
            get
            {
                return this.MMSAddressField;
            }
            set
            {
                this.MMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DateFirstSeen
        {
            get
            {
                return this.DateFirstSeenField;
            }
            set
            {
                this.DateFirstSeenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DateOfPorting
        {
            get
            {
                return this.DateOfPortingField;
            }
            set
            {
                this.DateOfPortingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NoteCodes
        {
            get
            {
                return this.NoteCodesField;
            }
            set
            {
                this.NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NoteDescriptions
        {
            get
            {
                return this.NoteDescriptionsField;
            }
            set
            {
                this.NoteDescriptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TokensUsed
        {
            get
            {
                return this.TokensUsedField;
            }
            set
            {
                this.TokensUsedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GPPL2Error", Namespace="http://www.serviceobjects.com")]
    public partial class GPPL2Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://www.serviceobjects.com")]
    public partial class Provider : object
    {
        
        private string NameField;
        
        private string CityField;
        
        private string StateField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string LineTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LineType
        {
            get
            {
                return this.LineTypeField;
            }
            set
            {
                this.LineTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://www.serviceobjects.com")]
    public partial class Contact : object
    {
        
        private string NameField;
        
        private string AddressField;
        
        private string CityField;
        
        private string StateField;
        
        private string PostalCodeField;
        
        private string PhoneTypeField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string SICCodeField;
        
        private string SICDescField;
        
        private string QualityScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneType
        {
            get
            {
                return this.PhoneTypeField;
            }
            set
            {
                this.PhoneTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SICCode
        {
            get
            {
                return this.SICCodeField;
            }
            set
            {
                this.SICCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SICDesc
        {
            get
            {
                return this.SICDescField;
            }
            set
            {
                this.SICDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string QualityScore
        {
            get
            {
                return this.QualityScoreField;
            }
            set
            {
                this.QualityScoreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="GPPL2Service.IGeoPhonePlus")]
    public interface IGeoPhonePlus
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_QUERYGETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_QUERYGETXMLAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_QUERYGETJSON", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_QUERYGETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_QUERYGETJSONAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/PhoneInfo_QUERYGETJSON", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/PhoneInfo_QUERYGETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> PhoneInfo_QUERYGETJSONAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_GETXML", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_GETXMLAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_GETJSON", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_GETJSONAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_POSTJSON", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_POSTJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_POSTJSONAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_POSTXML", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo_POSTXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_POSTXMLAsync(string PhoneNumber, string TestType, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfo", ReplyAction="http://www.serviceobjects.com/IGeoPhonePlus/GetPhoneInfoResponse")]
        System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfoAsync(string PhoneNumber, string TestType, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGeoPhonePlusChannel : GPPL2Service.IGeoPhonePlus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GeoPhonePlusClient : System.ServiceModel.ClientBase<GPPL2Service.IGeoPhonePlus>, GPPL2Service.IGeoPhonePlus
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GeoPhonePlusClient() : 
                base(GeoPhonePlusClient.GetDefaultBinding(), GeoPhonePlusClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GeoPhonePlusSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoPhonePlusClient(EndpointConfiguration endpointConfiguration) : 
                base(GeoPhonePlusClient.GetBindingForEndpoint(endpointConfiguration), GeoPhonePlusClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoPhonePlusClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GeoPhonePlusClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoPhonePlusClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GeoPhonePlusClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoPhonePlusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_QUERYGETXMLAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_QUERYGETXMLAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_QUERYGETJSONAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_QUERYGETJSONAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> PhoneInfo_QUERYGETJSONAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.PhoneInfo_QUERYGETJSONAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_GETXMLAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_GETXMLAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_GETJSONAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_GETJSONAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_POSTJSONAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_POSTJSONAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfo_POSTXMLAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfo_POSTXMLAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<GPPL2Service.PhoneInfoResponse> GetPhoneInfoAsync(string PhoneNumber, string TestType, string LicenseKey)
        {
            return base.Channel.GetPhoneInfoAsync(PhoneNumber, TestType, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeoPhonePlusSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeoPhonePlusSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/GPPL2/api.svc/GeoPhonePlusSoap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GeoPhonePlusClient.GetBindingForEndpoint(EndpointConfiguration.GeoPhonePlusSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GeoPhonePlusClient.GetEndpointAddress(EndpointConfiguration.GeoPhonePlusSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            GeoPhonePlusSoap,
        }
    }
}
